-- ============================================================
-- Operations admin letters archive (admin only)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.operations_admin_letter_sequences (
  year integer PRIMARY KEY,
  last_sequence integer NOT NULL DEFAULT 0,
  prefix text NOT NULL DEFAULT 'OPS',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.operations_admin_letters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  letter_number text NOT NULL UNIQUE,
  letter_type text NOT NULL DEFAULT 'outgoing'
    CHECK (letter_type IN ('outgoing', 'incoming', 'internal', 'decision', 'circular', 'memo')),
  subject text NOT NULL,
  content_summary text,
  correspondent_entity text,
  letter_date date NOT NULL DEFAULT CURRENT_DATE,
  reference_number text,
  archive_status text NOT NULL DEFAULT 'active'
    CHECK (archive_status IN ('active', 'archived', 'expired')),
  is_signed boolean NOT NULL DEFAULT false,
  signed_at timestamptz,
  signed_by text,
  requires_response boolean NOT NULL DEFAULT false,
  response_due_date date,
  related_letter_id bigint REFERENCES public.operations_admin_letters(id) ON DELETE SET NULL,
  file_path text,
  file_name text,
  file_mime text,
  tags text[] NOT NULL DEFAULT '{}'::text[],
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ops_admin_letters_type ON public.operations_admin_letters (letter_type);
CREATE INDEX IF NOT EXISTS idx_ops_admin_letters_status ON public.operations_admin_letters (archive_status);
CREATE INDEX IF NOT EXISTS idx_ops_admin_letters_date ON public.operations_admin_letters (letter_date DESC);
CREATE INDEX IF NOT EXISTS idx_ops_admin_letters_signed ON public.operations_admin_letters (is_signed);
CREATE INDEX IF NOT EXISTS idx_ops_admin_letters_ref ON public.operations_admin_letters (reference_number);

CREATE TABLE IF NOT EXISTS public.operations_admin_letter_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  letter_id bigint NOT NULL REFERENCES public.operations_admin_letters(id) ON DELETE CASCADE,
  action text NOT NULL,
  details text,
  performed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ops_admin_letter_activity_letter ON public.operations_admin_letter_activity (letter_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.generate_operations_outgoing_letter_number(p_prefix text DEFAULT 'OPS')
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_year integer := EXTRACT(YEAR FROM CURRENT_DATE)::integer;
  v_seq integer;
  v_prefix text := COALESCE(NULLIF(trim(p_prefix), ''), 'OPS');
BEGIN
  IF public.get_jwt_role() <> 'admin' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  INSERT INTO public.operations_admin_letter_sequences (year, last_sequence, prefix)
  VALUES (v_year, 0, v_prefix)
  ON CONFLICT (year) DO NOTHING;

  UPDATE public.operations_admin_letter_sequences
  SET last_sequence = last_sequence + 1,
      prefix = v_prefix,
      updated_at = now()
  WHERE year = v_year
  RETURNING last_sequence INTO v_seq;

  RETURN v_prefix || '/' || v_year::text || '/' || lpad(v_seq::text, 3, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.set_operations_admin_letters_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ops_admin_letters_updated_at ON public.operations_admin_letters;
CREATE TRIGGER trg_ops_admin_letters_updated_at
BEFORE UPDATE ON public.operations_admin_letters
FOR EACH ROW EXECUTE FUNCTION public.set_operations_admin_letters_updated_at();

DO $$
DECLARE
  t text;
  policy_name text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'operations_admin_letter_sequences',
    'operations_admin_letters',
    'operations_admin_letter_activity'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);

    policy_name := t || '_admin_only_select';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.get_jwt_role() = ''admin'')',
      policy_name, t
    );

    policy_name := t || '_admin_only_insert';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (public.get_jwt_role() = ''admin'')',
      policy_name, t
    );

    policy_name := t || '_admin_only_update';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (public.get_jwt_role() = ''admin'') WITH CHECK (public.get_jwt_role() = ''admin'')',
      policy_name, t
    );

    policy_name := t || '_admin_only_delete';
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_name, t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR DELETE TO authenticated USING (public.get_jwt_role() = ''admin'')',
      policy_name, t
    );
  END LOOP;
END $$;

INSERT INTO storage.buckets (id, name, public)
VALUES ('operations-admin-letters', 'operations-admin-letters', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "operations_admin_letters_storage_select" ON storage.objects;
CREATE POLICY "operations_admin_letters_storage_select"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'operations-admin-letters' AND public.get_jwt_role() = 'admin');

DROP POLICY IF EXISTS "operations_admin_letters_storage_insert" ON storage.objects;
CREATE POLICY "operations_admin_letters_storage_insert"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'operations-admin-letters' AND public.get_jwt_role() = 'admin');

DROP POLICY IF EXISTS "operations_admin_letters_storage_update" ON storage.objects;
CREATE POLICY "operations_admin_letters_storage_update"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'operations-admin-letters' AND public.get_jwt_role() = 'admin')
WITH CHECK (bucket_id = 'operations-admin-letters' AND public.get_jwt_role() = 'admin');

DROP POLICY IF EXISTS "operations_admin_letters_storage_delete" ON storage.objects;
CREATE POLICY "operations_admin_letters_storage_delete"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'operations-admin-letters' AND public.get_jwt_role() = 'admin');
