-- Generated from Excel files in data/import
-- Generated at: 2026-04-01T11:23:24.690Z

insert into public.installation_staff_members (full_name, role, city, is_active)
values
  ('علي محمد حميد', 'technician', 'عويريج', true),
  ('محمد فارس كامل', 'technician', 'عويريج', true),
  ('علي محيسن', 'technician', 'عويريج', true),
  ('محمد قحطان اسماعيل', 'technician', 'جكوك', true),
  ('حسن هادي', 'technician', 'عويريج', true),
  ('سامر حميد عبد الله', 'technician', 'اليوسفية', true),
  ('محمد ماجد خليبص', 'technician', 'عويريج', true),
  ('سجاد علي عبد زيد', 'technician', 'عويريج', true),
  ('حمزة ابراهيم رحيل', 'technician', 'عويريج', true),
  ('عمار علي جاسم', 'technician', 'عويريج', true),
  ('حسين علي جاسم', 'technician', 'عويريج', true),
  ('عباس حاتم عباس', 'technician', 'عويريج', true),
  ('احمد صالح مهدي', 'technician', 'الدورة', true),
  ('اركان ثائر البير', 'technician', 'الدورة ( Leader )', true),
  ('بسام اركان  ثائر', 'technician', 'الدورة', true),
  ('حمزة طالب علوان', 'technician', 'الكرادة', true),
  ('علي مشتاق طالب', 'technician', 'الدورة', true),
  ('عمر لطيف ابراهيم', 'technician', 'الكرادة', true),
  ('حسين قحطان', 'technician', 'السيدية ( Leader )', true),
  ('محمد ذياب خليل', 'technician', 'عويريج', true),
  ('مصطفى نصيف جاسم', 'technician', 'عويريج', true),
  ('مصطفى قحطان جميغ', 'technician', 'السيدية', true),
  ('عمر انور', 'technician', 'عويريج', true),
  ('منتظر قيس ياسر', 'technician', 'البياع', true),
  ('كرز الدين فاضل عباس', 'technician', 'حي الجهاد', true),
  ('طه زكي محيي', 'technician', 'البلديات', true),
  ('احمد كريم حسان', 'technician', 'حي العامل', true),
  ('امجد عادل حسين', 'technician', 'عويريج', true),
  ('حيدر علي حميد', 'technician', 'عويريج', true),
  ('محمد فلاح حسن', 'technician', 'عويريج', true),
  ('احمد محسن عباس', 'technician', 'عويريج', true),
  ('سيف عباس حسن', 'technician', 'جسر ديالى', true),
  ('علي ماجد حسن', 'technician', 'جسر ديالى', true),
  ('قاسم سعدي احمد', 'technician', 'جسر ديالى', true),
  ('خضر صباح تايه', 'technician', 'الزعفرانية', true),
  ('فراس كريم', 'technician', 'جسر ديالى ( Leader )', true),
  ('مصطفى قاسم رزوقي', 'technician', 'بسماية', true),
  ('محمد علي', 'technician', 'بغداد الجديدة ( Leader )', true),
  ('حسين كاظم مناتي', 'technician', 'الزعفرانية', true),
  ('علي خليل جهاد', 'technician', 'ديالى', true),
  ('انس داوود', 'technician', 'عويريج', true),
  ('محمد صدام', 'technician', 'خان بني سعد ( قرب ديالى )', true),
  ('مصطفى زكي محي', 'technician', 'الوزيرية', true),
  ('مصطفى تايه سفاح', 'technician', 'الشعب', true),
  ('يحيى صباح تايه', 'technician', 'الزعفرانية', true),
  ('مهند عادل حسين', 'technician', 'عويريج', true),
  ('منتظر حامد', 'technician', null, true),
  ('احمد محمد جاسم دوش', 'technician', 'محمودية', true),
  ('عبد الله علي عبيد', 'technician', 'عويريج', true),
  ('عبد العزيز كريم شرقي', 'technician', 'محمودية', true),
  ('حسين صادق', 'technician', 'عويريج', true),
  ('مؤيد جهاد', 'technician', 'حي الاعلام', true),
  ('محمد صلاح', 'technician', 'الدورة', true),
  ('زيد عزت عبد', 'technician', 'الدورة', true),
  ('حامد خالد عبد', 'technician', 'حي الجهاد', true),
  ('عبد الله محمد عبد الهادي', 'technician', 'الدورة', true),
  ('علي خيري', 'technician', 'حي الجهاد', true),
  ('ابراهيم مجبل جاسم', 'technician', 'الحلة', true),
  ('احمد عماد سبع', 'technician', 'الحلة', true),
  ('امير حامد خضير', 'technician', 'الحلة', true),
  ('حيدر طالب', 'technician', 'الحلة', true),
  ('طاهر صباح', 'technician', 'الحلة', true),
  ('سامر شاكر محمود', 'technician', 'كربلاء', true),
  ('محمد صفاء محمود', 'technician', 'كربلاء', true),
  ('نور الدين صفاء محمود', 'technician', 'كربلاء', true),
  ('كرار احمد شبلاوي', 'technician', 'كربلاء', true),
  ('امجد خالد', 'technician', 'كربلاء', true),
  ('امجد عيدان عبد الحسن', 'technician', 'كربلاء', true),
  ('محمد حاكم عبد الكاظم', 'technician', 'كربلاء', true),
  ('علي كاظم محمد', 'technician', 'كربلاء', true),
  ('حيدر تركي', 'technician', 'كربلاء ( Leader )', true),
  ('كرار باسم', 'technician', 'كربلاء', true),
  ('اكرم جواد', 'technician', 'كربلاء', true),
  ('اكرم عبد الصادق عبد الصمد', 'technician', 'كربلاء', true),
  ('امير حسين شاكر', 'technician', 'النجف', true),
  ('امير حيدر موسى', 'technician', 'النجف', true),
  ('زيد كامل سعدون', 'technician', 'النجف', true),
  ('اثير مظفر جميل', 'technician', 'النجف', true),
  ('كرار ابراهيم عبد', 'technician', 'النجف', true),
  ('صادق حامد كاظم', 'technician', 'النجف', true),
  ('حسن علي', 'technician', 'النجف ( Leader )', true),
  ('حسين غازي جعفر', 'technician', 'النجف', true),
  ('عبد الرحمن فلاح مهيدي', 'technician', 'الرمادي', true),
  ('امير سعود حميد', 'technician', 'الرمادي', true),
  ('عادل مطلب صبار', 'technician', 'الرمادي', true),
  ('ميثم ناصر سحاب', 'technician', 'الرمادي', true),
  ('يوسف قهرمان سلیمان', 'technician', 'اربيل', true),
  ('علي وليد خضير', 'technician', 'اربيل', true),
  ('يونس صباح', 'technician', 'اربيل', true),
  ('كاروان محمد علي', 'technician', 'اربيل', true),
  ('عبد الباري ابراهيم محمد', 'technician', 'اربيل', true),
  ('محمود مظفر محمد', 'technician', 'اربيل', true),
  ('عبد الرحمن طه خضير', 'technician', 'اربيل', true),
  ('ابراهيم عبد الحميد', 'technician', 'اربيل', true),
  ('سليم نجم مطشر', 'technician', 'الكوت', true),
  ('ضرغام علي زعلان', 'technician', 'كوت', true),
  ('ابراهيم حسن مريح', 'technician', 'كوت', true),
  ('وسام محسن', 'technician', 'البصرة', true)
on conflict (full_name) do update
set role = excluded.role,
    city = excluded.city,
    is_active = excluded.is_active;

update public.installation_staff_members
set is_active = false
where full_name not in (
  'علي محمد حميد',
  'محمد فارس كامل',
  'علي محيسن',
  'محمد قحطان اسماعيل',
  'حسن هادي',
  'سامر حميد عبد الله',
  'محمد ماجد خليبص',
  'سجاد علي عبد زيد',
  'حمزة ابراهيم رحيل',
  'عمار علي جاسم',
  'حسين علي جاسم',
  'عباس حاتم عباس',
  'احمد صالح مهدي',
  'اركان ثائر البير',
  'بسام اركان  ثائر',
  'حمزة طالب علوان',
  'علي مشتاق طالب',
  'عمر لطيف ابراهيم',
  'حسين قحطان',
  'محمد ذياب خليل',
  'مصطفى نصيف جاسم',
  'مصطفى قحطان جميغ',
  'عمر انور',
  'منتظر قيس ياسر',
  'كرز الدين فاضل عباس',
  'طه زكي محيي',
  'احمد كريم حسان',
  'امجد عادل حسين',
  'حيدر علي حميد',
  'محمد فلاح حسن',
  'احمد محسن عباس',
  'سيف عباس حسن',
  'علي ماجد حسن',
  'قاسم سعدي احمد',
  'خضر صباح تايه',
  'فراس كريم',
  'مصطفى قاسم رزوقي',
  'محمد علي',
  'حسين كاظم مناتي',
  'علي خليل جهاد',
  'انس داوود',
  'محمد صدام',
  'مصطفى زكي محي',
  'مصطفى تايه سفاح',
  'يحيى صباح تايه',
  'مهند عادل حسين',
  'منتظر حامد',
  'احمد محمد جاسم دوش',
  'عبد الله علي عبيد',
  'عبد العزيز كريم شرقي',
  'حسين صادق',
  'مؤيد جهاد',
  'محمد صلاح',
  'زيد عزت عبد',
  'حامد خالد عبد',
  'عبد الله محمد عبد الهادي',
  'علي خيري',
  'ابراهيم مجبل جاسم',
  'احمد عماد سبع',
  'امير حامد خضير',
  'حيدر طالب',
  'طاهر صباح',
  'سامر شاكر محمود',
  'محمد صفاء محمود',
  'نور الدين صفاء محمود',
  'كرار احمد شبلاوي',
  'امجد خالد',
  'امجد عيدان عبد الحسن',
  'محمد حاكم عبد الكاظم',
  'علي كاظم محمد',
  'حيدر تركي',
  'كرار باسم',
  'اكرم جواد',
  'اكرم عبد الصادق عبد الصمد',
  'امير حسين شاكر',
  'امير حيدر موسى',
  'زيد كامل سعدون',
  'اثير مظفر جميل',
  'كرار ابراهيم عبد',
  'صادق حامد كاظم',
  'حسن علي',
  'حسين غازي جعفر',
  'عبد الرحمن فلاح مهيدي',
  'امير سعود حميد',
  'عادل مطلب صبار',
  'ميثم ناصر سحاب',
  'يوسف قهرمان سلیمان',
  'علي وليد خضير',
  'يونس صباح',
  'كاروان محمد علي',
  'عبد الباري ابراهيم محمد',
  'محمود مظفر محمد',
  'عبد الرحمن طه خضير',
  'ابراهيم عبد الحميد',
  'سليم نجم مطشر',
  'ضرغام علي زعلان',
  'ابراهيم حسن مريح',
  'وسام محسن'
);

insert into public.installation_vehicles (vehicle_number, vehicle_type, location, responsible_staff_id, status)
select
  v.vehicle_number,
  v.vehicle_type,
  v.location,
  s.id,
  v.status
from (
  values
    ('10238', 'starex', 'بغداد', 'حمزة ابراهيم رحيل', 'available'),
    ('12487', 'starex', 'اربيل', 'محمد مظفر', 'available'),
    ('48891', 'starex', 'بغداد', 'مصطفى قحطان', 'available'),
    ('14084', 'starex', 'صيانات', 'علي خيري', 'available'),
    ('58332', 'starex', 'بغداد', null, 'available'),
    ('59736', 'starex', 'بغداد', 'احمد محمد جاسم', 'available'),
    ('71393', 'starex', '—', 'قاسم سعدي احمد', 'available'),
    ('20537', 'starex', '—', 'كاروان محمد علي', 'available'),
    ('41595', 'starex', '—', 'حامد خالد عبد', 'available'),
    ('27726', 'starex', '—', 'عبد الله محمد عبد الهادي', 'available'),
    ('57418', 'starex', 'اربيل', 'يوسف قهرمان', 'available'),
    ('52159', 'starex', '—', 'زيد عزت عبد', 'available'),
    ('23329', 'starex', '—', 'ابراهيم مجبل جاسم', 'available'),
    ('32258', 'starex', '—', 'كرار احمد شبلاوي', 'available'),
    ('14957', 'starex', 'كربلاء', 'امجد خالد', 'available'),
    ('68073', 'starex', '—', 'اثير مظفر جميل', 'available'),
    ('18645', 'starex', '—', 'عبد الرحمن محمد', 'available'),
    ('59918', 'starex', '—', 'سامر حميد', 'available'),
    ('25045', 'starex', '—', 'مؤيد جهاد', 'available'),
    ('15884', 'starex', '—', 'سليم نجم مطشر', 'available'),
    ('26177', 'nissan', 'بغداد', 'محمد صلاح', 'available'),
    ('26182', 'nissan', '—', 'حمزة طالب علوان', 'available'),
    ('26270', 'nissan', 'بغداد', 'سيف عباس', 'available'),
    ('27102', 'nissan', '—', 'فراس كريم حسان', 'available'),
    ('27305', 'nissan', '—', 'علي خليل جهاد', 'available'),
    ('26882', 'nissan', 'بغداد', 'عباس حاتم', 'available'),
    ('26308', 'nissan', 'بابل', 'احمد عماد سبع', 'available'),
    ('26045', 'nissan', 'كربلاء', 'نور الدين', 'available'),
    ('26874', 'nissan', '—', 'طه زكي', 'available'),
    ('26417', 'nissan', 'النجف', 'صادق جامد', 'available'),
    ('26414', 'nissan', '—', 'حسن علي ابراهيم', 'available'),
    ('26090', 'nissan', '—', 'عادل مطلب صبار', 'available'),
    ('29503', 'nissan', '—', 'محمد علي محسن', 'available'),
    ('29507', 'nissan', '—', 'حيدر تركي', 'available'),
    ('29564', 'nissan', '—', 'حسين قحطان', 'available'),
    ('29773', 'nissan', '—', 'امجد عادل', 'available'),
    ('29736', 'nissan', '—', 'انس داوود', 'available'),
    ('29942', 'nissan', '—', null, 'available'),
    ('29931', 'nissan', '—', 'اركان ثائر', 'available')
) as v(vehicle_number, vehicle_type, location, staff_name, status)
left join public.installation_staff_members s on s.full_name = v.staff_name
on conflict (vehicle_number) do update
set vehicle_type = excluded.vehicle_type,
    location = excluded.location,
    responsible_staff_id = excluded.responsible_staff_id,
    status = excluded.status,
    updated_at = now();

insert into public.inventory_item_templates (department_code, category, item_name, required_quantity, sort_order, is_active)
values
  ('installation', 'tools', 'منشار تخريم', 1, 10, true),
  ('installation', 'tools', 'دريل همر', 1, 20, true),
  ('installation', 'tools', 'بوكس براغي صغير', 1, 30, true),
  ('installation', 'tools', 'سيت المتعدد برينة', 1, 40, true),
  ('installation', 'tools', 'دريل شحن', 1, 50, true),
  ('installation', 'tools', 'كاوية + كابسة + محولة', 1, 60, true),
  ('installation', 'tools', 'درج', 1, 70, true),
  ('installation', 'tools', 'مروحة شحن', 1, 80, true),
  ('installation', 'tools', 'جرخ كنتور', 1, 90, true),
  ('installation', 'tools', 'مقصات سرير', 1, 100, true),
  ('installation', 'tools', 'بطل جك سرير', 1, 110, true),
  ('installation', 'tools', 'هيادرولك الكنتور', 1, 120, true),
  ('installation', 'tools', 'مساطر مرآة', 1, 130, true),
  ('installation', 'tools', 'بوري تعلاكة', 1, 140, true),
  ('installation', 'tools', 'سكة مجر عادي قياس 25', 1, 150, true),
  ('installation', 'tools', 'سكة مجر عادية قياس 30', 1, 160, true),
  ('installation', 'tools', 'سكة مجر عادية قياس 35', 1, 170, true),
  ('installation', 'tools', 'سكة مجر عادية قياس 40', 1, 180, true),
  ('installation', 'tools', 'سكة مجر حفر 35CM', 1, 190, true),
  ('installation', 'tools', 'سكة حفر 40', 1, 200, true),
  ('installation', 'tools', 'سكة هايدرولك سلايد 30', 1, 210, true),
  ('installation', 'tools', 'سكة هايدرولك سلايد 35', 1, 220, true),
  ('installation', 'tools', 'سكة هايدرولك سلايد 40', 1, 230, true),
  ('installation', 'tools', 'سكة هيدرولك قراصة حمراء 35', 1, 240, true),
  ('installation', 'tools', 'سكة هيدرولك قراصة حمراء 40', 1, 250, true),
  ('installation', 'tools', 'نرمادة عدلة', 1, 260, true),
  ('installation', 'tools', 'نرمادة عدلة هايدرولك', 1, 270, true),
  ('installation', 'tools', 'نرمادة نصف', 1, 280, true),
  ('installation', 'tools', 'نرمادة نصف هايدرولك', 1, 290, true),
  ('installation', 'tools', 'نرمادة عالية', 1, 300, true),
  ('installation', 'tools', 'نرمادة عالية هايدرولك', 1, 310, true),
  ('installation', 'tools', 'معالج', 1, 320, true),
  ('installation', 'tools', 'زواية', 1, 330, true),
  ('installation', 'tools', 'طوبة سرير', 1, 340, true),
  ('installation', 'tools', 'قاعدة طبلة', 1, 350, true),
  ('installation', 'tools', 'باجات', 1, 360, true),
  ('installation', 'tools', 'ارجل وسطية - خاصة بكادر الصيانة', 1, 370, true),
  ('installation', 'tools', 'حمالة بوري', 1, 380, true),
  ('installation', 'tools', 'حمالة مراة عامودية', 1, 390, true)
on conflict (department_code, category, item_name) do update
set required_quantity = excluded.required_quantity,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();
